<?php

namespace ContainerG2uhEWJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFraisforfaitService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.w9jrdkL.App\Entity\Fraisforfait' shared service.
     *
     * @return \App\Entity\Fraisforfait
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.w9jrdkL": it references class "App\\Entity\\Fraisforfait" but no such service exists.');
    }
}
