<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Fichefrais extends \App\Entity\Fichefrais implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Fichefrais' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Fichefrais' . "\0" . 'mois', '' . "\0" . 'App\\Entity\\Fichefrais' . "\0" . 'nbjustificatifs', '' . "\0" . 'App\\Entity\\Fichefrais' . "\0" . 'montantvalide', '' . "\0" . 'App\\Entity\\Fichefrais' . "\0" . 'datemodif', '' . "\0" . 'App\\Entity\\Fichefrais' . "\0" . 'idetat', '' . "\0" . 'App\\Entity\\Fichefrais' . "\0" . 'idutilisateur', '' . "\0" . 'App\\Entity\\Fichefrais' . "\0" . 'lesFicheFraisSec'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Fichefrais' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Fichefrais' . "\0" . 'mois', '' . "\0" . 'App\\Entity\\Fichefrais' . "\0" . 'nbjustificatifs', '' . "\0" . 'App\\Entity\\Fichefrais' . "\0" . 'montantvalide', '' . "\0" . 'App\\Entity\\Fichefrais' . "\0" . 'datemodif', '' . "\0" . 'App\\Entity\\Fichefrais' . "\0" . 'idetat', '' . "\0" . 'App\\Entity\\Fichefrais' . "\0" . 'idutilisateur', '' . "\0" . 'App\\Entity\\Fichefrais' . "\0" . 'lesFicheFraisSec'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Fichefrais $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getMois(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMois', []);

        return parent::getMois();
    }

    /**
     * {@inheritDoc}
     */
    public function setMois(string $mois): \App\Entity\Fichefrais
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMois', [$mois]);

        return parent::setMois($mois);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbjustificatifs(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbjustificatifs', []);

        return parent::getNbjustificatifs();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbjustificatifs(?int $nbjustificatifs): \App\Entity\Fichefrais
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbjustificatifs', [$nbjustificatifs]);

        return parent::setNbjustificatifs($nbjustificatifs);
    }

    /**
     * {@inheritDoc}
     */
    public function getMontantvalide(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontantvalide', []);

        return parent::getMontantvalide();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontantvalide(?string $montantvalide): \App\Entity\Fichefrais
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontantvalide', [$montantvalide]);

        return parent::setMontantvalide($montantvalide);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatemodif(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatemodif', []);

        return parent::getDatemodif();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatemodif(?\DateTimeInterface $datemodif): \App\Entity\Fichefrais
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatemodif', [$datemodif]);

        return parent::setDatemodif($datemodif);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdetat(): ?\App\Entity\Etat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdetat', []);

        return parent::getIdetat();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdetat(?\App\Entity\Etat $idetat): \App\Entity\Fichefrais
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdetat', [$idetat]);

        return parent::setIdetat($idetat);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdutilisateur(): ?\App\Entity\Utilisateur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdutilisateur', []);

        return parent::getIdutilisateur();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdutilisateur(?\App\Entity\Utilisateur $idutilisateur): \App\Entity\Fichefrais
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdutilisateur', [$idutilisateur]);

        return parent::setIdutilisateur($idutilisateur);
    }

    /**
     * {@inheritDoc}
     */
    public function getLesFicheFraisSec(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLesFicheFraisSec', []);

        return parent::getLesFicheFraisSec();
    }

    /**
     * {@inheritDoc}
     */
    public function addLesFicheFraisSec(\App\Entity\UtilisateurSecondaire $lesFicheFraisSec): \App\Entity\Fichefrais
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addLesFicheFraisSec', [$lesFicheFraisSec]);

        return parent::addLesFicheFraisSec($lesFicheFraisSec);
    }

    /**
     * {@inheritDoc}
     */
    public function removeLesFicheFraisSec(\App\Entity\UtilisateurSecondaire $lesFicheFraisSec): \App\Entity\Fichefrais
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeLesFicheFraisSec', [$lesFicheFraisSec]);

        return parent::removeLesFicheFraisSec($lesFicheFraisSec);
    }

}
